#num-1 = invalid, uses minus symbol
#1num = invalid, starts with number
#firstname = valid
#lastname = valid
#age = valid
#_1 = valid, you can use underscores in any part of the name
#country = valid
#city = valid
#first_name = valid
#last_name = valid
#capital_city = valid
#year_2021 = valid, you can have numbers beside underscores without any problem
#last-name = invalid, you cannot use the minus symbol when naming variables
#user$name = invalid, uses the $ symbol
#year2021 = valid
#current_year_2021 = valid
#birth_year = valid
#sur@name = invalid, you cannot use the @ symbol
#num2 = valid
#num1 = valid