name = input("Enter your name: ")
phone_number = input("Enter your phone number: ")
age = input("Enter your age: ")
age = int(age)
height = input("Enter your height: ")
height = float(height)
eircode = input("Enter your Eircode")
